### ISSUE TITLE
Can you share iphone dataloader scripts?

### ISSUE THREAD

**Issue by akatigre** [Caoang327/HexPlane#11]
Hi @Caoang327! Thank you for open sourcing this amazing project

I am trying to reproduce 3d dynamic models on casual video dataset, and I would also like to experiment your model on IPhone dataset. Can you kindly share the source code for loading the IPhone dataset?

**Comment by Caoang327** [comment]
Hi. 
The code is here https://drive.google.com/file/d/1hkSVyy05f1pP4sDJSjqNFUobpkSVGT_g/view?usp=sharing

**Comment by akatigre** [comment]
Thank you very much! I am grateful for your help.&nbsp;
Wish you have a nice day.

Best regards,
Yoonjeon Kim

-----Original Message-----From: "Caoang327" ***@***.***&gt;To: "Caoang327/HexPlane" ***@***.***&gt;;Cc: "JennyJeoni" ***@***.***&gt;; "Author" ***@***.***&gt;;Sent: 2023-09-25 (월) 05:05:38 (UTC+09:00)Subject: Re: [Caoang327/HexPlane] Can you share iphone dataloader scripts? (Issue #11)
Hi.The code is here https://drive.google.com/file/d/1hkSVyy05f1pP4sDJSjqNFUobpkSVGT_g/view?usp=sharing https://drive.google.com/file/d/1hkSVyy05f1pP4sDJSjqNFUobpkSVGT_g/view?usp=sharing
