### ISSUE TITLE
testvideo.mp4  no video!

### ISSUE THREAD

**Issue by xuyaojian123** [Caoang327/HexPlane#13]
I run `python main.py config=./config/dnerf_slim.yaml`，When the program finishes, testvideo.map4 has no video。

![image](https://github.com/Caoang327/HexPlane/assets/51220835/316da428-e382-4af9-8907-c165321601b5)

![image](https://github.com/Caoang327/HexPlane/assets/51220835/43afb7e1-e6e9-4355-99cf-0a8a2f32da40)

**Comment by Caoang327** [comment]
Hi. It might be because of the wrong format of this video. You can upload it to some online mp4 converter and convert it to mp4.
