### ISSUE TITLE
Pretrained checkpoints

### ISSUE THREAD

**Issue by anhtuanhsgs** [Caoang327/HexPlane#14]
Hi,

Thanks for the great work! We are trying to develope another work using your results.

Can you please provide the pretrained model for the Nvidia dataset and the the Iphone dataset from your training?

Thanks!

**Comment by Caoang327** [comment]
Thanks for interests. We don't train on Nvidia dataset. In general, it is a quick method for reconstruction so that I don't feel it is necessary to release checkpoint, otherwise you have some troubles when running it?
