### ISSUE TITLE
MultiGPU setup

### ISSUE THREAD

**Issue by akumar005** [Caoang327/HexPlane#15]
Hi,

Thank you for the awesome work. I have a rather a general problem. Can you help me in setting up this code on multigpu? Though I am able to train the model by replacing .model to .model.module at most places,  while I reload the checkpoint, I get the error in "get_optparam_groups" indicating it does not have support for nn.DataParallel (while training i used model.module.get_optparam_group and it worked). Can you please help in this? 

Thanks in advance.

**Comment by Caoang327** [comment]
Hi. Sorry for the late reply. Do you solve it or shall I investigate this problem now?

**Comment by akumar005** [comment]
Hi,

Thank you for the reply. I have solved this issue.

**Comment by akumar005** [comment]
But I have run into another issue. I am getting this white circular region in my rendering images. This is also happening for some of 
![issuehexplane](https://github.com/Caoang327/HexPlane/assets/80036421/062904dd-bb2e-4c32-b210-8ee1ef1cd5fc)
the case of training pose too.

**Comment by Caoang327** [comment]
It looks like a sphere. Which coordinates are you using?

**Comment by akumar005** [comment]
I am using HexPlane model, which I believe to be in Cartesian coordinate systems.

**Comment by Caoang327** [comment]
Hi. This is quite strange and I suspect it is from the coordinate and sampling range. It may not sample anything inside this sphere
