### ISSUE TITLE
Results reproduction on D-NeRF dataset

### ISSUE THREAD

**Issue by JasonLSC** [Caoang327/HexPlane#16]
Hi, thank you for your great work. 
During my attempt to replicate the results on NeRF Synthetic, I encountered misalignment. For example, on the 'mutant' dataset, I could only achieve a PSNR of 31dB on test views, whereas the appendix indicates that HexPlane can reach 33+dB. 
Any suggestion on hyperparmeter setting to reproduce your results? For now, I set ''model.time_grid_init=38 and     model.time_grid_final=149".

**Comment by Caoang327** [comment]
That might be too big. Can you try init = 8 and final 16?

**Comment by JasonLSC** [comment]
Thanks, I will give it a try.
