### ISSUE TITLE
How to calculate scene_bbox_min/max in my own data

### ISSUE THREAD

**Issue by Ben-chen-alt** [Caoang327/HexPlane#2]
How to calculate scene_bbox_min/max in my own data?

**Comment by Caoang327** [comment]
Hi. The scene bbox_min/max could be calculated based on near/far values for each input view. See this function about how to compute it based on near/far values https://github.com/Caoang327/HexPlane/blob/35efe64f7fdcba48c432eb0b5d58a5cb5b05ab4c/hexplane/dataloader/dnerf_dataset.py#L132.
