### ISSUE TITLE
Need config for 100k iterations

### ISSUE THREAD

**Issue by skalien** [Caoang327/HexPlane#21]
The paper mentions there is a HexPlane✝ models trained with 100k iterations. 
Can you please provide the config file for it (for the N3D dataset)?

Thanks.

**Comment by Caoang327** [comment]
It is here https://github.com/Caoang327/HexPlane/blob/3f7e630b1b4dad92c2281fec6c1f964231f4576d/config/nv3d.yaml

**Comment by skalien** [comment]
`upsample_list, update_emptymask_list, stage_{1,2,3}_iteration` doesn't need to be changed?

**Comment by Caoang327** [comment]
Sorry copy the wrong one: https://github.com/Caoang327/HexPlane/blob/6f51635d091df4d2086392625da96f11195c9f67/config/nv3d.yaml
