### ISSUE TITLE
Getting all gray images when training Plenoptic dataset  with general MLP setting

### ISSUE THREAD

**Issue by anona-R** [Caoang327/HexPlane#22]
Hi, I was trying out both HexPlane and Hexplane_slim. However, the plenoptic dataset only works with Hexplane_slim. Please help me to resolve this issue.

my nv3d.yaml file looks like this. 

systems:
  basedir: "./logs"
  vis_every: 5000

model:
  N_voxel_init: 262144
  time_grid_init: 31
  time_grid_final: 300
  upsampling_type: aligned
  upsample_list: [70000, 140000, 210000]
  update_emptymask_list: [50000, 100000, 150000, 220000]
  fusion_one: "multiply"
  fusion_two: "multiply"
  density_n_comp: [12, 12, 12]
  app_n_comp: [24, 24, 24]
  fea2denseAct: softplus #relu
  app_view_pe: 2
  app_fea_pe: 2

  TV_weight_density: 0.0005
  TV_weight_app: 0.0005

data:
  datadir:"./Datasets_3D/Neural_3D_Video/coffee_martini"
  dataset_name: neural3D_NDC
  scene_bbox_min: [-2.5, -2.0, -1.0]
  scene_bbox_max: [2.5, 2.0, 1.0]
  N_vis: 5

**Comment by Caoang327** [comment]
Hi. Can you try to change fusion_two from multiple to sum? If both of them are multiply, you may want to have a better initialization value for the plane to control the magnitude of valued.

**Comment by anona-R** [comment]
Hi, thank you so much for helping with this issue. It works now.  Your work is really inspiring and thanks for the great work.
