### ISSUE TITLE
I want to know how much GB of graphics memory I would need to run dynamic video data？

### ISSUE THREAD

**Issue by linmi1** [Caoang327/HexPlane#23]
I tried a dynamic video on a 24G, 3090 graphics card, but it showed that the graphics memory was insufficient. If the input frame rate was reduced, the result would be very poor.
Does anyone tried the dynamic video data,could you please tell me how much GB of graphics memory I would need???

**Comment by linmi1** [comment]
when I run this code : `all_imgs = torch.zeros(len(videos) - 1, 300, img_wh[-1] * img_wh[-2], 3)`
will get:
`Process finished with exit code 137`

**Comment by Caoang327** [comment]
Hi. It may not be the GPU problem as the `all_imgs = torch.zeros(len(videos) - 1, 300, img_wh[-1] * img_wh[-2], 3)` doesn't use GPUs. It may related to CPU memories. How much memory (RAM) are you using?

**Comment by linmi1** [comment]
> Hi. It may not be the GPU problem as the `all_imgs = torch.zeros(len(videos) - 1, 300, img_wh[-1] * img_wh[-2], 3)` doesn't use GPUs. It may related to CPU memories. How much memory (RAM) are you using?

yes ,we can add .to("cuda") to transfer it to cuda ,but it also need too much memory.
