### ISSUE TITLE
Inconsistancy between paper and implementation

### ISSUE THREAD

**Issue by xxnz** [Caoang327/HexPlane#24]
Hey Ang, 

Firstly, thanks for the great work! 

However, here is something that I find difficult to understand and I hope you were able to provide some clarity around it. Have a look at the flow chart you had in the paper:
 
![image](https://github.com/user-attachments/assets/284fa4ae-329c-45bc-b3fc-f2d3b7e7722b)

Based on the way the chart is drawn, it suggests that both the density and RGB/appearance are computed based on the same set of 6 feature planes. 

However, this is not the case in the implementation, where two separate sets of hex planes are initiated to handle density and appearance independently:

![image](https://github.com/user-attachments/assets/2da321b4-9458-4241-8510-b10e4a3c4d87)

As I am unable to find any clarification around this in the paper, could you please help us understand whether this discrepancy is intentional and explain the motivation behind this approach? Thanks.

**Comment by Caoang327** [comment]
Hi. First sorry for the late response.

It is a great question and yes you are totally correct. This is inconsistent to the original paper: we use two separate planes for opacity and colors. Having two separate planes is a kind of common practice of explicit representations and we didn't realize it will lead to misunderstanding. Sorry for that.

In general: I don't think sampling from one set of planes or sampling separately from two sets of planes will lead to much difference. You can image we stack two set of planes along the feature dimensions into one single planes, and train MLP to ignore the inputs from other planes. For example, for opacity MLP, it could basically ignore the features from color planes and still regress the opacities. This will lead to the same results as the current implementations. 

Performance-wise, having separate planes requires roughly 2x samples, which might be less efficient.

**Comment by xxnz** [comment]
Hi Ang,

Many thanks for the reply.

I did not know that using two separate sets of planes was a 'common practice' in the realm of explicit representations. But I did test the setup as you described above, where only one set of Hex planes was used to regress both densities and appearance. The results are not great - which is why I brought this issue up in the first place.  

I will close the thread now, but I do hope that you could clarify this inconsistency in your manuscript or elsewhere for the reader.

Thanks.

**Comment by Caoang327** [comment]
Thanks for that. I will give a look at single set of hexplane once getting time
