### ISSUE TITLE
How can I train the model in a new real world images dataset

### ISSUE THREAD

**Issue by sincerely1** [Caoang327/HexPlane#3]
Your work is awesome. I want to train your work in a images dataset. I don't konw which config I should use? I think I should use nv3d config. But this config is train for video dataset. I don't know the code modify the code. Could you give me some advice?Thank you!

**Comment by Caoang327** [comment]
Thanks for it. The central part of training on own dataset is to write a dataset class like neural_3D_dataset_NDC.py in dataloader folder, which could read "rays", "rgbs" and "times" data using __get_item__() functions. You may also want to specify the "scene_bbox_min/max" and "self.near_far" attributes, which would be useful for rendering. 

After that, you can call this class with "get_train_dataset" function in __init__.py file for dataloader. 

Rember to adjust the models' settings based on your own data and results. 

Feel free to ask any information. Thanks

**Comment by Akash-Kumbar** [comment]
> Thanks for it. The central part of training on own dataset is to write a dataset class like neural_3D_dataset_NDC.py in dataloader folder, which could read "rays", "rgbs" and "times" data using **get_item**() functions. You may also want to specify the "scene_bbox_min/max" and "self.near_far" attributes, which would be useful for rendering.
> 
> After that, you can call this class with "get_train_dataset" function in **init**.py file for dataloader.
> 
> Rember to adjust the models' settings based on your own data and results.
> 
> Feel free to ask any information. Thanks

Hey, can you explain more about the near, far, and scene bbox min, and max attributes and how can I set this according to my dataset? Is it related to camera poses or the c2w matrix? Please explain more about it.

thank you

**Comment by Caoang327** [comment]
Hi:

The scene box min/max is the x,y,z boundary, in which we model the current scene. The near, far is the range we sample points along the rays.
