### ISSUE TITLE
How to generate a camera pose for a novel view?

### ISSUE THREAD

**Issue by jelleopard** [Caoang327/HexPlane#4]
Hello, first of all thanks for sharing you work!
How to generate a camera pose like the one you show in the demo of https://caoang327.github.io/HexPlane/. Synthesis Results for Dynamic Scenes.
Can you provide the code to generate the new pose?

**Comment by jelleopard** [comment]
https://caoang327.github.io/HexPlane/videos/Virtual_Camera_Cut_roasted_beef.mp4

**Comment by Caoang327** [comment]
They are in this function: https://github.com/Caoang327/HexPlane/blob/e170008e6847f0cdb86c27257b00a0a3beb60525/hexplane/dataloader/neural_3D_dataset_NDC.py#LL266C21-L266C21

**Comment by jelleopard** [comment]
Thank you for your reply.
