### ISSUE TITLE
About iPhone dataset

### ISSUE THREAD

**Issue by xingy038** [Caoang327/HexPlane#6]
Thanks for your valuable work. I notice that in the paper you test an iPhone dataset, but the code does not include this data loader. Could you please share this data loader? or give me some advice to create this data loader?

**Comment by Caoang327** [comment]
Hi.
The code is here https://drive.google.com/file/d/1hkSVyy05f1pP4sDJSjqNFUobpkSVGT_g/view?usp=sharing
